
paginate: 5
pagination_path: "/page:num" 

blogname: 邓彪的博客
motto: 有一种东西叫做梦想
tilte: dengbiao.github.io
url: http://dengbiao.github.io
permalink: /:categories/:year/:month/:day/:title.html

pygments: true

